### ISSUE TITLE
Launcher for UNIX-based systems?

### ISSUE THREAD

**Issue by tdrkDev** [VimeWorld/LauncherUI#1]
Why no launcher for these systems? I can't play on macOS, emulators are not supported by launcher! You have not stored any paths to play with Mac. Many launchers have cross-platform code, but you are distributing launcher only for Windows. If download and launch launcher.jar, downloaded by VimeWorld.exe, it will give null pointer exception. Shitcode? :D

`2020-09-05 20:42:09.679 [SEVERE] Error in main()
java.lang.NullPointerException
	at net.xtrafrancyz.vl.i. (Unknown Source)
	at net.xtrafrancyz.vl.i. (Unknown Source)
	at net.xtrafrancyz.vl.VimeWorld.main(Unknown Source)`

**Comment by xtrafrancyz** [comment]
We have a bunch of native code for our Anti-Cheat system that works only on Windows. We are unable to support this on all available platforms. So there is no point in writing cross-platform code in launcher.
